name: Build font and specimen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo apt-get install libcairo2-dev libfreetype6-dev
        sudo add-apt-repository ppa:sile-typesetter/sile
        sudo apt-get update
        sudo apt-get install sile
    - uses: actions/cache@v2
      name: Cache Python dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-v2-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-v2-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build font
      run: |
        make
    - name: Build specimen
      run: make specimen
    - name: Rename font
      run: mv fonts/ttf/Gulzar-Regular.ttf .
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Gulzar
        path: |
          Gulzar-Regular.ttf
          specimen/specimen.pdf
